// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMpu3SWuNv6hSv4Sfvfat0ErLbGTN2EnA',
    appId: '1:755262446989:web:78b87893f2565a776231c4',
    messagingSenderId: '755262446989',
    projectId: 'aegis-ai-4cb59',
    authDomain: 'aegis-ai-4cb59.firebaseapp.com',
    storageBucket: 'aegis-ai-4cb59.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA80xi3OFiVn2_sOyyTRNUvls0CYWuNON8',
    appId: '1:755262446989:android:7bf999a96c0af68f6231c4',
    messagingSenderId: '755262446989',
    projectId: 'aegis-ai-4cb59',
    storageBucket: 'aegis-ai-4cb59.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNi2O_BkiNV_GYUd_zvOh3s-_6WLZ-4Ho',
    appId: '1:755262446989:ios:2d3125d6dffc4c826231c4',
    messagingSenderId: '755262446989',
    projectId: 'aegis-ai-4cb59',
    storageBucket: 'aegis-ai-4cb59.firebasestorage.app',
    iosBundleId: 'com.example.aegisAi',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNi2O_BkiNV_GYUd_zvOh3s-_6WLZ-4Ho',
    appId: '1:755262446989:ios:2d3125d6dffc4c826231c4',
    messagingSenderId: '755262446989',
    projectId: 'aegis-ai-4cb59',
    storageBucket: 'aegis-ai-4cb59.firebasestorage.app',
    iosBundleId: 'com.example.aegisAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMpu3SWuNv6hSv4Sfvfat0ErLbGTN2EnA',
    appId: '1:755262446989:web:6c0e0a6e1676b5256231c4',
    messagingSenderId: '755262446989',
    projectId: 'aegis-ai-4cb59',
    authDomain: 'aegis-ai-4cb59.firebaseapp.com',
    storageBucket: 'aegis-ai-4cb59.firebasestorage.app',
  );
}
